import './bootstrap';
import Alpine from 'alpinejs';
import {
    ArrowRight,
    ArrowUpRight,
    BadgeCheck,
    BadgeHelp,
    Blocks,
    BookOpenCheck,
    Bot,
    Boxes,
    CalendarCheck2,
    CalendarDays,
    CalendarRange,
    ChartNoAxesCombined,
    Check,
    CheckCircle2,
    CircleCheck,
    Database,
    FileText,
    GraduationCap,
    Info,
    Landmark,
    LayoutDashboard,
    LogIn,
    Mail,
    MapPin,
    MapPinCheck,
    Menu,
    MessageCircle,
    MessageCircleMore,
    MessagesSquare,
    MonitorSmartphone,
    Moon,
    NotebookTabs,
    Plus,
    Presentation,
    Quote,
    ReceiptText,
    RefreshCw,
    ScanFace,
    School,
    ShieldAlert,
    ShieldCheck,
    Smartphone,
    Sparkles,
    Sun,
    UserCheck,
    UsersRound,
    WalletCards,
    WandSparkles,
    Warehouse,
    Wrench,
    createIcons,
} from 'lucide';

window.Alpine = Alpine;

Alpine.start();

const icons = {
    ArrowRight,
    ArrowUpRight,
    BadgeCheck,
    BadgeHelp,
    Blocks,
    BookOpenCheck,
    Bot,
    Boxes,
    CalendarCheck2,
    CalendarDays,
    CalendarRange,
    ChartNoAxesCombined,
    Check,
    CheckCircle2,
    CircleCheck,
    Database,
    FileText,
    GraduationCap,
    Info,
    Landmark,
    LayoutDashboard,
    LogIn,
    Mail,
    MapPin,
    MapPinCheck,
    Menu,
    MessageCircle,
    MessageCircleMore,
    MessagesSquare,
    MonitorSmartphone,
    Moon,
    NotebookTabs,
    Plus,
    Presentation,
    Quote,
    ReceiptText,
    RefreshCw,
    ScanFace,
    School,
    ShieldAlert,
    ShieldCheck,
    Smartphone,
    Sparkles,
    Sun,
    UserCheck,
    UsersRound,
    WalletCards,
    WandSparkles,
    Warehouse,
    Wrench,
};

const renderIcons = () => createIcons({ icons });

if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', renderIcons);
} else {
    renderIcons();
}
